spring.application.name=auth-service
server.port=${PORT:8082}

spring.datasource.url=${LEXO_AUTH_DB_URL:jdbc:postgresql://localhost:5434/lexo_auth}
spring.datasource.username=${LEXO_AUTH_DB_USER:postgres}
spring.datasource.password=${LEXO_AUTH_DB_PASS:postgres}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

eureka.client.service-url.defaultZone=${LEXO_EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.hostname=${LEXO_EUREKA_HOSTNAME:localhost}

lexo.auth-secret=${AUTH_SECRET:troque-esta-chave-em-producao-com-no-minimo-32-bytes}
lexo.jwt-expiration-minutes=${JWT_EXP_MINUTES:720}
lexo.totp-enc-key=${TOTP_ENC_KEY:}
lexo.base-url=${BASE_URL:http://localhost:8080}
lexo.cors.allowed-origins=${LEXO_CORS_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:4200}

spring.data.redis.host=${LEXO_REDIS_HOST:localhost}
spring.data.redis.port=${LEXO_REDIS_PORT:6380}

spring.rabbitmq.host=${LEXO_RABBIT_HOST:localhost}
spring.rabbitmq.port=${LEXO_RABBIT_PORT:5673}
spring.rabbitmq.username=${LEXO_RABBIT_USER:guest}
spring.rabbitmq.password=${LEXO_RABBIT_PASS:guest}
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.default-requeue-rejected=false

lexo.internal.api-key=${LEXO_INTERNAL_KEY:chave-interna-dev-trocar-em-producao}

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${LEXO_ZIPKIN:http://localhost:9411/api/v2/spans}
logging.pattern.level=%5p [%X{traceId:-},%X{spanId:-}]
