spring.application.name=discovery-server
server.port=8761

# Sendo o proprio registro, ele nao se registra nem busca em outro Eureka.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
